stages:
  data_ingestion:
    cmd: python src/CDC/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CDC/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/CDC/pipeline/stage_02_base_model.py
    deps:
      - src/CDC/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - INPUT_SHAPE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_model



  training:
    cmd: python src/CDC/pipeline/stage_04_training.py
    deps:
      - src/CDC/pipeline/stage_04_training.py
      - src/CDC/components/callbacks.py
      - config/config.yaml
      - artifacts/data/Chicken-fecal-images
      - artifacts/base_model
    params:
      - INPUT_SHAPE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/CDC/pipeline/stage_05_model_evaluation.py
    deps:
      - src/CDC/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data/Chicken-fecal-images
      - artifacts/training/model.h5dv