artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  unzip_dir: artifacts/data
  local_data_file: artifacts/data/data.zip
  

base_model:
  root_dir : artifacts/base_model
  base_model_path : artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/base_model_updated.h5
